### ISSUE TITLE
add varchar support

### ISSUE THREAD

**Issue by vrusua** [rjuju/pg_anonymize#10]
Hi there,

and thanks for the great job!

Could you please consider to add varchar support here, or?

I'm not an expert in C programming, but have you considered
```     if ((typid == UNKNOWNOID) && (att->atttypid == TEXTOID || att->atttypid == VARCHAROID)) ```
at the line
https://github.com/rjuju/pg_anonymize/blob/c730a2b177ecf28639f12fe6d7bc79cae0070ac8/pg_anonymize.c#L388

Thanks,
Ruslan

**Comment by rjuju** [comment]
Hi,

Thanks a lot!

About the code extract you're showing, it's only an exception that mimics postgres behavior when it has to decide of a datatype when none is provided, for instance:

``` 
rjuju=# with s as (select 'test' v) select pg_typeof(v) from s;
 pg_typeof
-----------
 text
(1 row)
```

That exception is not really something you should consider relying on for a predictable behavior.  This module is already compatible with varchar or any other type, the clean and correct solution being to explicitly cast the expression, e.g.:

```
rjuju=# create table t_anon(val varchar);
CREATE TABLE

rjuju=# insert into t_anon select 'value';
INSERT 0 1

rjuju=# security label for pg_anonymize on column t_anon.val is $$'test'$$;
ERROR:  XX000: The expression returns "unknown" type, but the  column is defined as "character varying"

rjuju=# security label for pg_anonymize on column t_anon.val is $$'test'::varchar$$;
SECURITY LABEL
```

**Comment by vrusua** [comment]
Hi again, and thank you for a quick reply,

unfortunately, I got stuck due to Postgres ERROR here, see an example of PSQL (Postgres 15) output for the last_name (varchar) based on docs:

``` 

api=# SECURITY LABEL FOR pg_anonymize ON COLUMN app.users.last_name IS $$substr(last_name, 1, 1) || '*****'$$;

ERROR:  The expression returns "text" type, but the  column is defined as "character varying" 

```

and the rule has not applied until the field type is preliminary changed from varchar to text.

Or did I miss something to make it working?

Thanks

**Comment by rjuju** [comment]
As I mentioned, you can control what will be the anonymization expression datatype with an explicit cast.

Reproducing your example, you can see that the expression you used raises an error, but casting the expression to varchar (using `::varchar`, or if you want a more standard way you can use `cast(... AS varchar)`) allows you to use it:

```
rjuju=# \d app.users
                        Table "app.users"
  Column   |       Type        | Collation | Nullable | Default
-----------+-------------------+-----------+----------+---------
 last_name | character varying |           |          |

rjuju=# SECURITY LABEL FOR pg_anonymize ON COLUMN app.users.last_name
        IS $$substr(last_name, 1, 1) || '*****'$$;
ERROR:  XX000: The expression returns "text" type, but the  column is defined as "character varying"

rjuju=# SECURITY LABEL FOR pg_anonymize ON COLUMN app.users.last_name
        IS $$(substr(last_name, 1, 1) || '*****')::varchar$$;
SECURITY LABEL

rjuju=# SECURITY LABEL FOR pg_anonymize ON ROLE rjuju
        IS 'anonymize';
SECURITY LABEL

rjuju=# TABLE app.users;
 last_name
-----------
 S*****
(1 row)

rjuju=# SECURITY LABEL FOR pg_anonymize ON COLUMN app.users.last_name
        IS $$cast(substr(last_name, 1, 1) || '*****2' AS varchar)$$;
SECURITY LABEL

rjuju=# TABLE app.users;
 last_name
-----------
 S*****2
(1 row)
```

Note that in the `::varchar` case you still need extra parenthesis to cast the resulting expression and not just the `'*****'` literal.

**Comment by rjuju** [comment]
Great news, I'm glad to hear that!
