### ISSUE TITLE
SECURITY LABEL does not apply to camelCase fields

### ISSUE THREAD

**Issue by thebinod7** [rjuju/pg_anonymize#13]
Hi there,

The SECURITY LABEL applies for database fields like name,phone but when I try to camelCase fields Eg: firstName, lastName I get an error saying "ERROR:  column "lastname" of relation "tbl_customers" does not exist". Curious if I am missing something.

Thanks.

**Comment by rjuju** [comment]
Hi,

It's supposed to be supported, and after a quick local test I confirm that it does.  What command did you use exactly?  From your error message I think that you got your column created in CamelCase as expected, but the SECURITY LABEL command was apparently not.  I'm assuming that the problem was the lack of double-quotes, ie you should use

```
SECURITY LABEL FOR pg_anonymize ON COLUMN tbl_customers."FirstName" IS ...
```

**Comment by thebinod7** [comment]
@rjuju Yes, is it possible to unmask fields. I didn't find it on doc. I would love to know if there are other features along with docs since I am going to use it on production.

**Comment by rjuju** [comment]
do you mean removing the anonymisation rule for a specific column? you can do that with setting `NULL` as security label (be careful, using `'NULL' ` is different, it means anonyming with a NULL value)

for the other features, I only implemented what is documented, which is mostly what I needed, making sure that it works as expected. if you need other features, feel free to open an issue and I will take care of those!

**Comment by thebinod7** [comment]
@rjuju I am facing another issue. I am connected to the database with Masked role. Now I cant perform write operation into database however Masked role has a 'Superuser' privilege.

**Comment by rjuju** [comment]
yes that's expected. an anonymised role becomes read only as a safety measure, since any write it would do could be based on fake data.
