### ISSUE TITLE
Does this work with AWS RDS?

### ISSUE THREAD

**Issue by Wombatpm** [rjuju/pg_anonymize#9]
Does this extension wort with AWS RDS or is it in the same boat as pg_anonymizer ?

**Comment by rjuju** [comment]
Amazon doesn't really inform extension authors when they add support for an extensions, so I won't have more information than you.  That being said I haven't done a first released yet (there's work in progress to add a lot of sanity checks and enforce read only snapshots when accessing an anonymized relations), so it would be surprising if they added it.
